apiVersion: v1
kind: Service
metadata:
  name: broken
  labels:
    appid: broken
spec:
  selector:
    appid: broken
  ports:
    - protocol: TCP
      name: broken
      port: 6379
      targetPort: 6379
